general {
    ignore_empty_input = true
    hide_cursor = true
}

auth {
    fingerprint:enabled = true
    fingerprint:ready_message = Scan fingerprint to unlock
    fingerprint:present_message = Scanning...
}

background {
    monitor =
    color = rgba(25, 25, 30, 1.0)
}

animations {
    enabled = false
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgba(100, 100, 180, 1.0)
    inner_color = rgba(40, 40, 50, 1.0)
    font_color = rgba(200, 200, 220, 1.0)
    font_family = RecMonoLinear Nerd Font Mono
    fade_on_empty = true
    placeholder_text = Enter password
    fail_text = <i>$FAIL ($ATTEMPTS)</i>
    position = 0, -20
    halign = center
    valign = center
}

text = cmd[update:1000] echo "<span foreground='##ff2222'>$(date)</span>"

label {
    monitor =
    text = Hi there, $USER
    color = rgba(200, 200, 200, 1.0)
    font_size = 25
    font_family = RecMonoLinear Nerd Font Mono

    position = 0, 80
    halign = center
    valign = center
}
