# Use Ctrl-a, not Ctrl-b, for prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Claude / Amp CLI compatibility settings
set -g allow-passthrough all
# set -g allow-passthrough on

set -ga terminal-features ",*:hyperlinks"
set -as terminal-features 'xterm*:extkeys'

set -s set-clipboard on
set -s extended-keys on

# Use vim keybinds
setw -g mode-keys vi

# Enable mouse mode
set -g mouse on

# Automatically set window title
set-window-option -g automatic-rename on
set-option -g set-titles on

# Default statusbar color
set-option -g status-style bg=colour237,fg=colour223

# Use | and - to split a window
unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Move around panes with hjkl
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Switch between panes using alt + arrow
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Use shift + arrow key to move between windows
bind -n S-Left  previous-window
bind -n S-Right next-window
